[[redirects]]
from = "/api/*"
to = "https://lr-resume.herokuapp.com/api/:splat"
status = 200

[[headers]]
for = "/api/*"
[headers.values]
# COMMENT: Multi-key header rules are expressed with multi-line strings
sec-fetch-site = 'cross-origin'


[[redirects]]
from = "/*"
to = "/index.html"
status = 200

